number = [10,90,20,30,40]
print(number)
number.append(100)
print(number)
number.extend([100,200,300])
print(number)
print(len(number))
print(sum(number))
print(max(number))
print(min(number))
number.sort()
print(number)
print(number[0])
print(number[-1])
print(number[4])
print(number[len(number)//2])